### PR TITLE
Develop 方威翔

### PR DESCRIPTION
**Pull request by owenfang0406**
Merging the following contents into main branch:

*API endpoints running on AWS production environment:
- http://52.74.43.7:3000/api/attractions?page=1
- http://52.74.43.7:3000/api/attractions?page=0&keyword=藝文館所
- http://52.74.43.7:3000/api/attractions?page=0&keyword=北
- http://52.74.43.7:3000/api/attraction/15

*adding a python file for initializng the raw data named "DataHandler.py"

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but response format of http://52.74.43.7:3000/api/attraction/15 is incorrect.

Solve this issue and re-request review.

**Comment by owenfang0406** [comment]
Fix the format with searching pure ID

**Review by cwpeng — CHANGES_REQUESTED** [review]
I see no fix.

**Comment by owenfang0406** [comment]
Sorry for asking to review again, the format is fixed from a list of many dicts to a dict of a single dict for searching with pure attraction ID.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
