### PR TITLE
Develop 方威翔

### PR DESCRIPTION
**Pull request by owenfang0406**
Pouring request into main branch
index.html url: http://52.74.43.7:3000/
api/categoris: http://52.74.43.7:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Cannot load more pages when we scroll down to the bottom.
2. Footer should not fix in the bottom of screen, just put under content.
3. Layout details in search bar and head titles: margin, padding.

**Comment by owenfang0406** [comment]
bugs fixed.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Only navigation bar should fix in the top of screen.
2. Put more attension on layout details.

**Comment by owenfang0406** [comment]
getting CSS and text fixed

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
