### PR TITLE
Develop 方威翔

### PR DESCRIPTION
**Pull request by owenfang0406**
pouring request for HW 5
index: http://52.74.43.7:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should show sign in dialog after we click 預定行程 without signing in.

**Comment by owenfang0406** [comment]
Fix the UI behavior on click "預定行程" in the condition of being not logged in.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your booking page show 登入/註冊 even if we have signed in.

**Comment by owenfang0406** [comment]
Fix the bug of showing log in btn after log in under no oder condition

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
